# Generated by Django 2.0.4 on 2018-04-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20180427_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodPost',
            new_name='Food',
        ),
    ]
