# Generated by Django 2.0.4 on 2018-04-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20180427_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rator', models.IntegerField(blank=True)),
                ('rated', models.IntegerField(blank=True)),
                ('rating', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='FoodCategory',
        ),
        migrations.AddField(
            model_name='food',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='food',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='food',
            name='owner',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
