# Generated by Django 2.0.4 on 2018-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20180428_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='firebase_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
