# Generated by Django 2.0.4 on 2018-04-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_firebaseuser_firebase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='owner',
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.FirebaseUser'),
        ),
    ]
