# Generated by Django 2.0.4 on 2018-04-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_auto_20180428_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
