# Generated by Django 2.0.4 on 2018-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_auto_20180428_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
