# Generated by Django 2.0.4 on 2018-04-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_auto_20180428_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_rated', to='foodapp.FirebaseUser'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_rator', to='foodapp.FirebaseUser'),
        ),
    ]
