# Generated by Django 2.0.4 on 2018-04-29 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20180428_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.Community'),
        ),
    ]
